#!/usr/bin/env bash
# Install nginx on your web-01 server Nginx should be listening on port 80
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
service nginx start
