#!/usr/bin/env bash
# installs Nginx server and redirects /redirect_me to 301 moved parmanently
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/pasignature permanent;/" /etc/nginx/sites-available/default
service nginx start
