#!/usr/bin/env bash
# nginx server and configures redirection
apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'
ufw allow 'OpenSSH'
echo "Holberton School" > /var/www/html/index.html
service nginx start

# Managing redirection
redir="server_name _;\n\n\tlocation \/redirect_me {\n\t\trewrite ^\/(.*)\$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n\t}\n"
sed -i "s/server_name _;/$redir/g" /etc/nginx/sites-available/default
service nginx restart
