#!/usr/bin/env bash
# shellcheck disable=SC2154
#add header X-Served-By XXXXX
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart