#!/usr/bin/env bash
#Install and configure HAproxy your lb-01 server.
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 1730-web-01 35.196.117.79:80 check\n\tserver 1730-web-02 35.185.59.148:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
