#!/usr/bin/env bash

# display "Holberton School" 10 times

k="0"

while [ $k -lt 10 ]
do
	if [ $k -eq 3 ]
	then
		echo "bad luck"
	elif [ $k -eq 7 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	k=$((k+1))
done
