#!/usr/bin/env bash
# configures nginx to run as nginx user
sudo sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-available/default
pkill -SIGKILL apache
chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
